#!/usr/bin/env bash

set -e
set -x

APP_HOME=/opt/app-root
APP_CONF=/etc/app-root
BASE_IMAGE=$1
IMAGE_NAME=$2

containerID=$(buildah from ${BASE_IMAGE})

trap "buildah rm $containerID" EXIT

buildah run "$containerID" -- mkdir ${APP_HOME}
buildah run "$containerID" -- mkdir ${APP_CONF}

buildah copy "$containerID" main ${APP_HOME}

buildah run "$containerID" -- chown -R 1001:0 ${APP_HOME} ${APP_CONF}
buildah run "$containerID" -- chmod -R g=u ${APP_HOME} ${APP_CONF}

buildah config --workingdir="${APP_HOME}" "$containerID"
buildah config --user 1001 "$containerID"
buildah config --port 8080 "$containerID"
buildah config --entrypoint ./main "$containerID"

buildah commit "$containerID" "${IMAGE_NAME}"
