#!/usr/bin/env bash

set -e
set -x

IMAGE_NAME=$1

containerID=$(buildah from quay.io/gsalgadoartola/ruby:2.6-1)

trap "buildah rm $containerID" EXIT

buildah run "$containerID" -- microdnf install rh-ruby26-ruby-devel gcc-c++ gcc git zlib-devel make patch redhat-rpm-config tar postgresql-devel libcurl-devel -y
buildah run "$containerID" -- microdnf clean all -y

buildah run "$containerID" -- mkdir -p /home/jenkins
buildah run "$containerID" -- mkdir -p /home/jenkins/cache/ruby

buildah config --env 'HOME=/home/jenkins' "$containerID"
buildah config --env 'PATH=/opt/rh/rh-ruby26/root/usr/local/bin:/opt/rh/rh-ruby26/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' "$containerID"
buildah config --env 'LD_LIBRARY_PATH=/opt/rh/rh-ruby26/root/usr/local/lib64:/opt/rh/rh-ruby26/root/usr/lib64' "$containerID"
buildah config --env 'MANPATH=/opt/rh/rh-ruby26/root/usr/local/share/man:/opt/rh/rh-ruby26/root/usr/share/man' "$containerID"
buildah config --env 'PKG_CONFIG_PATH=/opt/rh/rh-ruby26/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby26/root/usr/lib64/pkgconfig' "$containerID"
buildah config --env 'XDG_DATA_DIRS=/opt/rh/rh-ruby26/root/usr/local/share:/opt/rh/rh-ruby26/root/usr/share' "$containerID"

buildah run "$containerID" -- gem install bundler -v 1.17.2
buildah run "$containerID" -- bundle config path /home/jenkins/cache/ruby
buildah run "$containerID" -- gem install bundler -v 2.1.4

buildah config --workingdir="/home/jenkins" "$containerID"

buildah commit "$containerID" "${IMAGE_NAME}"
